name: CI

on:
  push:
    branches:
      - master

env:
  PORT: "3001"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies (Backend)
        run: npm install
        working-directory: ./express-backend

      - name: Run Tests (Backend)
        run: npm run test
        working-directory: ./express-backend
        
      - name: Job complete
        run: echo "Job complete"
